import { Contract } from './contract';

export const CONTRACTS: Contract[] = [
  {
    id: 1,
    grantorName: 'Tech Innovations Inc.',
    projectName: 'Green Energy Solutions',
    courseName: 'Renewable Energy Engineering',
    employeeId: 1,
    employeeGivenName: 'John',
    employeeSurname: 'Doe',
    beginDate: new Date('2019-02-01'),
    endDate: new Date('2020-02-01'),
    informDeadlineOfFirstRecess: new Date('2019-08-01'),
    informDeadlineOfSecondRecess: new Date('2020-01-15'),
  },
  {
    id: 2,
    grantorName: 'Global Health Foundation',
    projectName: 'Vaccine Research Program',
    courseName: 'Medical Biotechnology',
    employeeId: 2,
    employeeGivenName: 'Jane',
    employeeSurname: 'Smith',
    beginDate: new Date('2018-05-01'),
    endDate: new Date('2019-05-01'),
    informDeadlineOfFirstRecess: new Date('2018-11-01'),
    informDeadlineOfSecondRecess: new Date('2019-04-15'),
  },
  {
    id: 3,
    grantorName: 'Cybernetics Corp.',
    projectName: 'AI for Good Initiative',
    courseName: 'Artificial Intelligence and Ethics',
    employeeId: 3,
    employeeGivenName: 'Jack',
    employeeSurname: 'Black',
    beginDate: new Date('2021-07-01'),
    endDate: new Date('2022-07-01'),
    informDeadlineOfFirstRecess: new Date('2022-01-01'),
    informDeadlineOfSecondRecess: new Date('2022-06-15'),
  },
  {
    id: 4,
    grantorName: 'Oceanic Preservation Society',
    projectName: 'Marine Biodiversity Project',
    courseName: 'Marine Biology and Conservation',
    employeeId: 4,
    employeeGivenName: 'Jill',
    employeeSurname: 'White',
    beginDate: new Date('2017-03-01'),
    endDate: new Date('2018-03-01'),
    informDeadlineOfFirstRecess: new Date('2017-09-01'),
    informDeadlineOfSecondRecess: new Date('2018-02-15'),
  },
  {
    id: 5,
    grantorName: 'Future Tech Leaders',
    projectName: 'Youth Robotics Program',
    courseName: 'Advanced Robotics and AI',
    employeeId: 5,
    employeeGivenName: 'Jim',
    employeeSurname: 'Green',
    beginDate: new Date('2022-10-01'),
    endDate: new Date('2023-10-01'),
    informDeadlineOfFirstRecess: new Date('2023-04-01'),
    informDeadlineOfSecondRecess: new Date('2023-09-15'),
  },
  {
    id: 6,
    grantorName: 'Urban Development Group',
    projectName: 'Smart Cities Initiative',
    courseName: 'Urban Planning and Sustainability',
    employeeId: 6,
    employeeGivenName: 'Jenny',
    employeeSurname: 'Brown',
    beginDate: new Date('2020-12-01'),
    endDate: new Date('2021-12-01'),
    informDeadlineOfFirstRecess: new Date('2021-06-01'),
    informDeadlineOfSecondRecess: new Date('2021-11-15'),
  },
  {
    id: 7,
    grantorName: 'International Art Council',
    projectName: 'Cultural Heritage Preservation',
    courseName: 'Art History and Restoration',
    employeeId: 7,
    employeeGivenName: 'Joe',
    employeeSurname: 'Grey',
    beginDate: new Date('2019-11-01'),
    endDate: new Date('2020-11-01'),
    informDeadlineOfFirstRecess: new Date('2020-05-01'),
    informDeadlineOfSecondRecess: new Date('2020-10-15'),
  },
  {
    id: 8,
    grantorName: 'Sustainable Agriculture Network',
    projectName: 'Organic Farming Expansion',
    courseName: 'Sustainable Agriculture Practices',
    employeeId: 8,
    employeeGivenName: 'Alice',
    employeeSurname: 'Murray',
    beginDate: new Date('2021-04-01'),
    endDate: new Date('2022-04-01'),
    informDeadlineOfFirstRecess: new Date('2021-10-01'),
    informDeadlineOfSecondRecess: new Date('2022-03-15'),
  },
  {
    id: 9,
    grantorName: 'Space Exploration Collective',
    projectName: 'Mars Habitat Simulation',
    courseName: 'Astrophysics and Space Engineering',
    employeeId: 9,
    employeeGivenName: 'Bob',
    employeeSurname: 'Johnson',
    beginDate: new Date('2019-07-01'),
    endDate: new Date('2020-07-01'),
    informDeadlineOfFirstRecess: new Date('2020-01-01'),
    informDeadlineOfSecondRecess: new Date('2020-06-15'),
  },
  {
    id: 10,
    grantorName: 'Quantum Computing Lab',
    projectName: 'Quantum Algorithms Research',
    courseName: 'Quantum Information Science',
    employeeId: 10,
    employeeGivenName: 'Cathy',
    employeeSurname: 'Lee',
    beginDate: new Date('2022-01-01'),
    endDate: new Date('2023-01-01'),
    informDeadlineOfFirstRecess: new Date('2022-06-01'),
    informDeadlineOfSecondRecess: new Date('2022-12-15'),
  },
  {
    id: 11,
    grantorName: 'Historical Society',
    projectName: 'Ancient Civilizations Study',
    courseName: 'Archaeology and Anthropology',
    employeeId: 11,
    employeeGivenName: 'David',
    employeeSurname: 'Kim',
    beginDate: new Date('2020-09-01'),
    endDate: new Date('2021-09-01'),
    informDeadlineOfFirstRecess: new Date('2021-03-01'),
    informDeadlineOfSecondRecess: new Date('2021-08-15'),
  },
  {
    id: 12,
    grantorName: 'Global Linguistics Forum',
    projectName: 'Endangered Languages Documentation',
    courseName: 'Linguistics and Language Preservation',
    employeeId: 12,
    employeeGivenName: 'Eva',
    employeeSurname: 'Martinez',
    beginDate: new Date('2018-06-01'),
    endDate: new Date('2019-06-01'),
    informDeadlineOfFirstRecess: new Date('2018-12-01'),
    informDeadlineOfSecondRecess: new Date('2019-05-15'),
  },
  {
    id: 13,
    grantorName: 'Ocean Cleanup Initiative',
    projectName: 'Plastic Pollution Reduction',
    courseName: 'Environmental Sciences and Policy',
    employeeId: 13,
    employeeGivenName: 'Frank',
    employeeSurname: 'Garcia',
    beginDate: new Date('2021-05-01'),
    endDate: new Date('2022-05-01'),
    informDeadlineOfFirstRecess: new Date('2021-11-01'),
    informDeadlineOfSecondRecess: new Date('2022-04-15'),
  },
  {
    id: 14,
    grantorName: 'Cyber Security Alliance',
    projectName: 'Data Protection Strategy',
    courseName: 'Cybersecurity and Digital Forensics',
    employeeId: 14,
    employeeGivenName: 'Grace',
    employeeSurname: 'Wang',
    beginDate: new Date('2019-08-01'),
    endDate: new Date('2020-08-01'),
    informDeadlineOfFirstRecess: new Date('2020-02-01'),
    informDeadlineOfSecondRecess: new Date('2020-07-15'),
  },
  {
    id: 15,
    grantorName: 'Artificial Intelligence Institute',
    projectName: 'AI in Healthcare',
    courseName: 'Health Informatics and AI',
    employeeId: 15,
    employeeGivenName: 'Henry',
    employeeSurname: 'Nguyen',
    beginDate: new Date('2022-03-01'),
    endDate: new Date('2023-03-01'),
    informDeadlineOfFirstRecess: new Date('2022-09-01'),
    informDeadlineOfSecondRecess: new Date('2023-02-15'),
  },
];
